### PR TITLE
Fix: render_docs() fails for Quarto website if package has non-Github URL

### LINKED ISSUE #318: Quarto website rendering fails if package has non-Github URL
I'm using altdoc 0.5.0.9000 (at 6d264b5) and attempting to render a Quarto website for a package that has non-Github URL and BugReports.

1. Create a new package with at least one roxygen2-documented function
2. In DESCRIPTION, set URL to a non-Github URL
3. Generate Rd documentation with `devtools::document()`
4. Run `altdoc::setup_docs("quarto_website")` and `altdoc::render_docs()`

``` r
altdoc::render_docs()
#> 
#> ── Basic files ─────────────────────────────────────────────────────────────────
#> ✔ 'README' imported.
#> 
#> ── Man pages ───────────────────────────────────────────────────────────────────
#> ℹ Found 1 man page to convert.
#> ⠙ Converting function reference 1/1: hello
#> Error in if (is.na(gh_link)) {: argument is of length zero
#> ✖ Converting function reference 1/1: hello [192ms]
```

<sup>Created on 2025-03-26 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

### PR DESCRIPTION
**Pull request by gardiners**
Fix #318 

Internal function `.gh_url()` should return NULL, rather than an empty vector, in the case that DESCRIPTION contains a URL or BugReports for a site other than Github.

### CODE REVIEW

File: R/import_man.R [hunk 1]
```diff
@@ -224,7 +224,7 @@
 
     # build URL
     gh_link <- .gh_url(".")
-    if (is.na(gh_link)) {
+    if (is.null(gh_link)) {
```
Comment (etiennebacher) [inline R/import_man.R:227]: I don't remember exactly the situation but I think we may end up with an `NA` here, so can you use `is.null(gh_link) || is.na(gh_link)` here?

**Review by etiennebacher — CHANGES_REQUESTED** [review]
Thanks, I thought this would conflict with the changes made in https://github.com/etiennebacher/altdoc/pull/314 but apparently the tests I added there pass here too, so it must be fine.

Can you add a test for this situation? You can take inspiration from the test in `test-render_docs()` L153. This will require you to create a fake minimal package in `testthat/examples` that will be almost identical to `testpkg.altdoc.noURL` but in this case it will contain a non-github URL in `DESCRIPTION`.

File: R/import_man.R (hunk 1 above)
Comment (gardiners) [reply R/import_man.R:227]: Will do!

**Review by etiennebacher — CHANGES_REQUESTED** [review]
Thanks! Last thing, can you add a bullet point in NEWS to describe the fix and add your github username and PR number?

**Comment by gardiners** [comment]
Done, thanks!

**Review by etiennebacher — APPROVED** [review]
