### PR TITLE
fix: does not require README.qmd for Quarto website

### LINKED ISSUE #292: [Quarto] Why requires `README.qmd`?
I am wondering if it is possible to skip rendering if there is already README.md.
`pkgdown` does not render the README, and I do not want to be forced to render it here.

`pkgdown` says rendering README is the responsibility of the user.

### PR DESCRIPTION
**Pull request by eitsupi**
Fix #292

I don't know if ideally we should render README.Rmd / qmd, but we should be able to fix the error for now anyway.

### CODE REVIEW

**Comment by vincentarelbundock** [comment]
I believe that Quarto requires a `index.qmd` file, otherwise it will not build the website.

Currently, we enforce `README.qmd` and copy that over as `index.qmd`. If you want to make that change, my guess is that you'll have to convert `README.md` to `index.qmd` and ensure that it contains valid Quarto code.

**Comment by eitsupi** [comment]
> I believe that Quarto requires a `index.qmd` file, otherwise it will not build the website.

No, Quarto CLI does not require any qmd file; if an index.html file is required, the source file can be index.md, index.Rmd, index.ipynb, or whatever.

**Comment by vincentarelbundock** [comment]
> No, Quarto CLI does not require any qmd file; if an index.html file is required, the source file can be index.md, index.Rmd, index.ipynb, or whatever.

Could this possibly depend on the output format? Here, we output to a "website" format.

If you're very confident and add a test for a toy repo without README.md that builds properly, we should of course move forward.

I'm just surprised because I think I remember adding this check because we got bug reports from users who had README.md but not README.qmd.

**Comment by eitsupi** [comment]
> Could this possibly depend on the output format? Here, we output to a "website" format.

I am sure Quarto will not require qmd files in any output format (otherwise it would be very difficult to use for users who only want to use ipynb, right?)
For example, there is not a qmd file in this repository (website source), but it has been around since before the Quarto CLI reached version 1.
https://github.com/rocker-org/website

**Comment by vincentarelbundock** [comment]
good example, thanks.

**Comment by eitsupi** [comment]
I believe the test project is now rendering correctly.

File: R/import_readme.R [hunk 1]
```diff
@@ -67,36 +60,27 @@
...
-  }
-
+  tar_file <- fs::path_join(c(tar_dir, "README.md"))
   src_file <- fs::path_join(c(src_dir, "README.md"))
   fs::file_copy(src_file, tar_file, overwrite = TRUE)
   .check_md_structure(tar_file)
 
+  # Add the index page which includes README.md
+  if (tool == "quarto_website") {
+    brio::write_lines(
```
Comment (vincentarelbundock) [inline R/import_readme.R:78]: Do we need to onboard a new dependency just for this call?

File: R/import_readme.R [hunk 2]
```diff
@@ -67,36 +60,27 @@
...
+      "{{< include README.md >}}",
+      fs::path_join(c(tar_dir, "index.md"))
```
Comment (vincentarelbundock) [inline R/import_readme.R:80]: Currently, users can include code blocks in `README.qmd` and that code will be rendered properly on the home page. When I tried that with your branch, my plot did not show up. Could this problem be related to this line?

File: inst/quarto_website/quarto_website.yml [hunk 3]
```diff
@@ -19,7 +19,7 @@ website:
     collapse-level: 1
     contents:
       - text: Home
-        file: index.qmd
```
Comment (vincentarelbundock) [inline inst/quarto_website/quarto_website.yml:22]: I think we should encourage `.qmd` by default, since `.md` makes some Quarto features unavailable.

File: tests/testthat/test-setup_docs.R [hunk 4]
```diff
@@ -61,6 +61,5 @@ test_that("quarto: README.qmd", {
   create_local_package()
   expect_false(file.exists("README.qmd"))
   setup_docs("quarto_website", overwrite = TRUE)
-  expect_true(file.exists("README.qmd"))
+  expect_false(file.exists("README.qmd"))
```
Comment (vincentarelbundock) [inline tests/testthat/test-setup_docs.R:64]: If there is nothing, we should return a Quarto document, because we are building a Quarto website and want users to be able to use all features on the home page.

I agree, of course, that this should be customizable and that users who want just README.md should be free to change this.

File: R/import_readme.R (hunk 1 above)
Comment (eitsupi) [reply R/import_readme.R:78]: There may be alternatives to not using brio if it is only used here, but given that it is a basic package and lightweight, there is little disadvantage to including it in the dependencies.

File: R/import_readme.R (hunk 2 above)
Comment (eitsupi) [reply R/import_readme.R:80]: Is it because the directory containing the image files has not been copied?
Where are the image files stored in the Git repository?

File: inst/quarto_website/quarto_website.yml (hunk 3 above)
Comment (eitsupi) [reply inst/quarto_website/quarto_website.yml:22]: > since `.md` makes some Quarto features unavailable.

For example?

File: tests/testthat/test-setup_docs.R (hunk 4 above)
Comment (eitsupi) [reply tests/testthat/test-setup_docs.R:64]: Related to the above, I don't think Quarto changes anything by file extension. (Again, why would a user who prefers ipynb want to use Quarto CLI if there are features that are only available in qmd?)

File: R/import_readme.R (hunk 2 above)
Comment (eitsupi) [reply R/import_readme.R:80]: I have rendered the website for the tinyplot package (https://github.com/grantmcdermott/tinyplot) and it seems to work fine.

Comment (vincentarelbundock) [reply R/import_readme.R:80]: Sounds great. Thanks a lot for taking the time to check!

File: inst/quarto_website/quarto_website.yml (hunk 3 above)
Comment (vincentarelbundock) [reply inst/quarto_website/quarto_website.yml:22]: I think I got confused with the order of operations. `index.md` is fine here because it will link to the `README.md` that we copied over, or to the `README.qmd` after it was rendered to `.md`. Sorry for the confusion.

File: R/import_readme.R (hunk 1 above)
Comment (vincentarelbundock) [reply R/import_readme.R:78]: Whats the benefit over:

```
writeLines(
    enc2utf8("{{< include README.md >}}"), 
    fs::path_join(c(tar_dir, "index.md"))
)
```

Comment (eitsupi) [reply R/import_readme.R]: Thanks for the suggestion.
`writeLines` is used many times in this package, that seems better choice.

**Comment by vincentarelbundock** [comment]
@etiennebacher This seems like a clear improvement to me. Do you want to check before merging?

**Comment by etiennebacher** [comment]
Thanks both, I'll take a quick look later today

**Comment by vincentarelbundock** [comment]
I can't seem to build the `marginaleffects` website with this branch. It's a rather complicated website which requires a `reticulate` virtual environment with some packages. So not sure either of you will want to try it, but I'll post the error message here.

At first glance, it seems related to the `index.md` change.


```r
[56/57] index.md
ERROR: You must use the .qmd extension for documents with executable code.

Stack trace:
    at Object.execute (file:///Applications/quarto/bin/quarto.js:40980:23)
    at renderExecute (file:///Applications/quarto/bin/quarto.js:78226:48)
    at renderFileInternal (file:///Applications/quarto/bin/quarto.js:78394:49)
    at eventLoopTick (ext:core/01_core.js:153:7)
    at async renderFiles (file:///Applications/quarto/bin/quarto.js:78262:17)
    at async renderProject (file:///Applications/quarto/bin/quarto.js:78672:25)
    at async Command.actionHandler (file:///Applications/quarto/bin/quarto.js:83271:32)
    at async Command.execute (file:///Applications/quarto/bin/quarto.js:8018:13)
    at async Command.parseCommand (file:///Applications/quarto/bin/quarto.js:7908:20)
    at async quarto (file:///Applications/quarto/bin/quarto.js:118497:9)
Error in `quarto::quarto_render()`:
✖ Error running quarto cli.
Caused by error:
! System command 'quarto' failed
Backtrace:
     ▆
  1. └─altdoc::render_docs(verbose = TRUE, freeze = TRUE)
  2.   └─altdoc:::.import_settings(...)
  3.     └─altdoc (local) finalize(settings, path, verbose, freeze)
  4.       └─quarto::quarto_render(...)
  5.         └─quarto:::quarto_run(args, echo = TRUE, quarto_bin = quarto_bin)
  6.           └─base::tryCatch(...)
  7.             └─base (local) tryCatchList(expr, classes, parentenv, handlers)
  8.               └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
  9.                 └─value[[3L]](cond)
 10.                   └─cli::cli_abort(msg, call = .call, parent = e)
 11.                     └─rlang::abort(...)
Execution halted
make: *** [website] Error 1
```

**Comment by eitsupi** [comment]
> I can't seem to build the `marginaleffects` website with this branch.

My guess is that this is where this comes from.
https://github.com/vincentarelbundock/marginaleffects/blob/64b946a6443ad143bb4d25bcc24357ec1e501bad/README.md?plain=1#L94-L101

````md
``` {latex}
````

I have never seen this notation before, what is the need for it?
If I understand correctly, this is not actually an executable code block, so I think this needs to be fixed.

**Comment by eitsupi** [comment]
Maybe you want to something like ```` ```{=latex} ````?

**Comment by vincentarelbundock** [comment]
Wow @eitsupi you're very good at this. Solves it. Thanks. I'll stop bugging you now.

**Comment by eitsupi** [comment]
Never mind, I am glad you were able to resolve the issue! (I know nothing about latex......)

**Comment by etiennebacher** [comment]
Thanks, LGTM, especially if it doesn't break the docs of other packages. I'll merge but any idea about the windows failure?

**Comment by eitsupi** [comment]
> any idea about the windows failure?

I have no idea.

Where `Rplots.pdf` comes from?
